# Generated by Django 3.2.5 on 2022-08-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remarcable_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='tagproductrelationship',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='tagproductrelationship',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
